### ISSUE TITLE
Single File Generator not invoked for CPS project

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#108]
My `VSPackage` is providing a `single file generator`.

```csharp
 [ProvideObject(typeof(AscxDesignerClassGenerator))]
    [CodeGeneratorRegistration(typeof(AscxDesignerClassGenerator), "AscxDesignerClassGenerator", vsContextGuids.vsContextGuidVCSProject, GeneratesDesignTimeSource = true)]
    public sealed class VsPackage : Package
    {

```

This generator works fine from a standard c# library project, when I set a custom tool on a file, it get's invoked. The same isn't true for my CPS project - it never gets invoked.

I have specified the capability in my targets:

```xml
<ProjectCapability Include="SingleFileGenerators;" />    
```

 Anything I am missing?

**Comment by adrianvmsft** [comment]
I think the problem may come from specifying `vsContextGuids.vsContextGuidVCSProject` that represents whether a Visual C# project is present in the IDE (per documentation).

However, in this case there is no Visual C# project, as CPS is a different project.
Browsing through the registry, I see that the 2 single file generators that work for CPS projects (resx and tt) are also registered as CPS:

```
HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0_Config\Generators\{13B669BE-BB05-4DDF-9536-439F39A36129}
```

So could you try specifying the CPS project type guid `{13B669BE-BB05-4DDF-9536-439F39A36129}` instead `vsContextGuids.vsContextGuidVCSProject` to see if that solves the problem?

Thanks,
Adrian

**Comment by dazinator** [comment]
Thanks @adrianvmsft  - I will give that a go!

**Comment by adrianvmsft** [comment]
Ok, I got it working and I sent pull request with detailed documentation. Please take a look and let me know what you think.

#118 

Some corrections to my reply above:
- You need to specify the project type guid of your project type (and not the CPS one as I mentioned in my previous reply); make sure you specify "{" and "}" around the Guid, otherwise it doesn't work
- If you have multiple project with the same project file extension (e.g. myproj that gets generated by default), you could run into an issue where the project type guid gets picked up from a different project type; so make sure your project file extension is unique on the system
- Also, the XAML rule for your file needs to support the "Generator" property, and its value specifies the Generator you are using

Hope this helps,
Adrian

**Comment by dazinator** [comment]
Thanks - will take a look at the PR now!

**Comment by adrianvmsft** [comment]
I am going to close this issue based on #118, please feel free to create a new one if you still run into problems.
