### ISSUE TITLE
VS2017 Extensibility Preview - No VCSTCompile build action

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#176]
Create a new project, and then include an existing vsct file into the project (rather than adding one via add new item dialog). The file is included, but there is no `VSCTCompile` listed under it's build actions.

![image](https://cloud.githubusercontent.com/assets/3176632/22862904/730084b8-f12f-11e6-9789-c4de4be52fd7.png)

Seems you should be able to set the build action like the following, but you can't:

![image](https://cloud.githubusercontent.com/assets/3176632/22862911/8abcea38-f12f-11e6-81ba-bdd7b04f0bdb.png)

If you then use the add new item wizard, to add a new command, that seems to then make the VSCTCompile build action available.

It seems that VSCTCompile build action should also become available for use when an existing .vsct file is included in the project, rather than just via the add new item template dialog.

**Comment by adrianvmsft** [comment]
Thanks for reporting this issue. Same problem happens with a standard VSIX project, so it is not specific to the Project System Extensibility.
I filed bug 385328 on the internal bug database against the VSSDK team, so I am going to close this issue.

**Comment by dazinator** [comment]
Ok, cheers

**Comment by Michael-Eng** [comment]
Hi dazinator - I looked into this issue. 

It's easy for us to add the VSCTCompile build action to the list. However, the process of moving a menu across isn't as simple as copying the vsct file. You also have to copy the source code for the VS package, and the resources. In addition, the VSCTCompile msbuild item has metadata on it which corresponds to the ProvideMenuResource attribute declared on the VS package. 

The concern is that if we add the VSCTCompile build action, it would only confuse users more when their vsct file fails to compile because of the other missing pieces to the menu. 

Given that it's hard to copy all the artifacts and get them all correct, we're inclined to not add the VSCTCompile build action. The thinking is that novice extension developers add a menu through the item templates and everything will be set correctly for them. Advanced users who know what they're doing can copy the files and manually copy the project file entries with their metadata.

**Comment by dazinator** [comment]
@Michael-Eng  - Thank you for the explanation. It struck me as a bug when I noticed it so thought I'd raise it.. but I can see your reasoning. I haven't worked with VSCT's that extensively to date, but.. i'm not really enjoying the experience so far! haha.
