### ISSUE TITLE
Microsoft.VSSDK.BuildTools nuget package does not migrate imports, leading to version mismatch

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#178]
I have no compile errors, but when I attempt to run / start my project type, I see this in the output window:

1>------ Build started: Project: DnnProjectSystem.ProjectTemplate, Configuration: Debug Any CPU ------
2>------ Build started: Project: DnnProjectSystem.ProjectType, Configuration: Debug Any CPU ------
2>C:\Users\Darrell\Source\Repos\DnnProjectSystem\src\packages\Microsoft.VSSDK.BuildTools.15.0.26201\tools\VSSDK\Microsoft.VsSDK.targets(75,5): warning VSSDK1018: Targets version (15.0.26201.0) and build task version (15.0.26206.0) do not match.  Restarting Visual Studio could help fix this issue.
========== Build: 1 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

I have tried a restart of VS, but no joy.

A normal build suceeds, I just can't launch.

Any pointers?

**Comment by dazinator** [comment]
I had to edit the targets file in the nuget package:

"src\packages\Microsoft.VSSDK.BuildTools.15.0.26201\tools\vssdk\Microsoft.VsSDK.targets"

to remove the check. 

It seems the targets file wants to make sure the version of the build task matches - however in my case, for some unknown reason, the version of the build task being used appears to be greater than the version of the nuget package. I am not sure why. The thing is I can't find a nuget package that matches the version of the task (15.0.26206.0) either.

**Comment by aienabled** [comment]
I've reported this issue recently https://github.com/Microsoft/VSProjectSystem/issues/170

**Comment by adrianvmsft** [comment]
I **think** there is a mismatch between the version that comes from the Nuget package (Microsoft.VsSDK.targests) and the Visual Studio you have installed on the box.
By default, the project type created with Visual Studio Extensibility uses what is installed by VS SDK. I suspect at some point you may have added that nuget reference (which is the right thing to do), but unfortunately that also left some dependencies on what is installed on the box.
So to fix this, you can try upgrading VS to the latest version or remove the dependency on what is installed on the box:
```xml
<VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
...
<Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" Condition="'$(VSToolsPath)' != ''" />
```
Hope this helps,
Adrian

**Comment by dazinator** [comment]
Hmm yeah, I think that nuget package should probably remove those entries on install.. I'll remove manually for now to see if that works.

**Comment by dazinator** [comment]
Yep so, installing the  `Microsoft.VSSDK.BuildTools.15.0.26201` package, leaves the existing import in the project file, and this seems to be what causes the conflict. Manually removing the other import fixes.

**Comment by adrianvmsft** [comment]
Nice, I am glad that it worked!

**Comment by dazinator** [comment]
There is a further issue.. In the `ProjectTemplate` project, there is a using task in the project file like this:

```

 <UsingTask TaskName="CreateZipPackage" AssemblyFile="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.Build.Tasks.dll" />

```

When you install the `Microsoft.VSSDK.BuildTools.15.0.26201` nuget package, the nuget package also contains the tasks assembly, but the project file is left looking at the one in VSTools. So you also have to update this line to resolve the task from the nuget package instead.

Looking at the targets file that the build tools nuget package provides, it does provide some environment variables for you:

```
 <UsingTask TaskName="SetVsSDKEnvironmentVariables" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
    <ParameterGroup>
      <ProjectDirectory Required="true" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs">
        System.Environment.SetEnvironmentVariable("VsSDKToolsPath", System.IO.Path.GetFullPath(ProjectDirectory + @"\..\tools\VSSDK\bin"),EnvironmentVariableTarget.Process);
        System.Environment.SetEnvironmentVariable("VsSDKSchemaDir", System.IO.Path.GetFullPath(ProjectDirectory + @"\..\tools\VSSDK\schemas"),EnvironmentVariableTarget.Process);
      </Code>
    </Task>
  </UsingTask>

```

However none of those environment variables point to `tools\vssdk\` folder within the package - which is where the tasks assembly lives: `Microsoft.VsSDK.Build.Tasks.dll` - which is a shame is this would have made it easier to update the `UsingTask` in the project file to be something like:

```
 <UsingTask TaskName="CreateZipPackage" AssemblyFile="$(VSSDKPath)\Microsoft.VsSDK.Build.Tasks.dll" />
```

So instead of the above, I have to use a path which I will have to update manually with each nuget package update:

```
  <UsingTask TaskName="CreateZipPackage" AssemblyFile="..\packages\Microsoft.VSSDK.BuildTools.15.0.26201\tools\VSSDK\Microsoft.VsSDK.Build.Tasks.dll" />
```

Can this be fixed?

**Comment by adrianvmsft** [comment]
I tried deleting that line and seems to be working fine, I wonder if it really is needed.
As I see, a new Project Template (created using the VSSDK project template) doesn't have it.
So, try removing it :)

The 2 projects that Project System Extensibility creates are underneath standard VSSDK projects, with some CPS specific content, so the structure should be the same:
- ProjectType1.ProjectTemplate1 - is VSSDK Project Template
- ProjectType1.ProjectType - is a VSSDK VSIX project with a significant CPS specific files

The problem is, in time they may go out of sync as VS SDK makes changes to the standard templates.

**Comment by dazinator** [comment]
> As I see, a new Project Template (created using the VSSDK project template) doesn't have it.

That's odd.. I just created a new one from the template, and can see the task in the project file for  `ProjectType1.ProjectTemplate1`:

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MinimumVisualStudioVersion>15.0</MinimumVisualStudioVersion>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">12.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <OldToolsVersion>4.0</OldToolsVersion>
    <UpgradeBackupLocation />
  </PropertyGroup>
  <UsingTask TaskName="CreateZipPackage" AssemblyFile="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.Build.Tasks.dll" />

I only recently installed the extensibility templates, but perhaps they have moved on again. How can I check to see if I have the latest extesibility templates installed?

**Comment by dazinator** [comment]
Oh wait - so you are saying it is in the extensibility templates, but doesn't need to be as its not in the VSSDK template..

**Comment by dazinator** [comment]
> The problem is, in time they may go out of sync as VS SDK makes changes to the standard templates.

Ouch!

**Comment by adrianvmsft** [comment]
Regarding the project system extensibility templates - you can check in the Extension Manager if there are updates available for the vsix. We haven't updated ours in a while, but we are going to do that soon, so I will also take a look if they need to be updated.

**Comment by dazinator** [comment]
Will rename this issue, based on problem we discovered.

**Comment by adrianvmsft** [comment]
I learned more about the warning:

It is a more generic issue, that can also be reproduced using standard VS SDK templates:
- New Vsix Project
- Build
- Add new item - custom command
- Build

For the first build, MSBuild.exe loads the build task that is shipped with Visual Studio. Adding the custom command adds the new version of the task dll. So the 2nd build loads the new targets, but continues to use the older version of task dll that is already loaded.

Unfortunately there is nothing we can do on our side about it, but there is a simple workaround:

**Workaround:** Restart Visual Studio or kill all instances of MSBuild.exe before building

Regarding the other issues you mentioned above, I updated the VSProjectExtensibility templates to be more consistent with the VSSDK templates, so that should fix the other issues you identified:
- Removed UsingTask CreateZipPackage
- Removed Scc tags (SccProjectName, SccLocalPath, etc)
- Updated the Visual Studio version specified in the templates so that Visual Studio doesn't cause upgrade during project creation (which caused the upgrade related tags to be added)

These fixes should be available in the next version of VSProjectExtensibility - so stay tuned :)

**Comment by dazinator** [comment]
Hi - just checking something, did you manage to fix this line in the templates:

``
<Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" Condition="'$(VSToolsPath)' != ''" />
```

Or rather, fix up the `Microsoft.VSSDK.BuildTools nuget package so that it swaps this import out for the version of `Microsoft.VsSDK.targets` that's delivered with the nuget package?

The issue at the moment is that when using the buildtools nuget package, the old imports do not match the version of the tasks.

**Comment by dazinator** [comment]
Ok so here is the problem: The project type project, uses the nuget package tasks, but imports the `vssdk` targets from the environment not from the nuget package. If you manually correct this, the other project (the project template project) also directly imports the `vssdk` targets from the environment - and it doesn't use the buildtools nuget package or have that referenced at all.

If you only fix up the project type project, the project template project still forces vssdk targets (and thus the vssdk tasks assembly) to be loaded from the environment,  which conflicts with the version of the tasks assembly that the nuget package wants.

So I think both these templates (project type, and project item) and any other CPS project template that imports `vssdk` targets, should all be updated so that they all import the vssdk targets from the same place (i.e preferably the nuget package). At the moment having some projects trying to use the nuget package, and other projects trying to use VSToolsPath is resulting in mismatching.

1. Updated project type project to import targets from nuget package.
2. still getting tasks "version" mismatch issue.
3. Checked project template project - this project template doesn't use 
The template for the project template project, directly imports this:

```
<Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" Condition="'$(VSToolsPath)' != ''" />
```

It doesn't use the build tools nuget package.

The template for the project type template, uses the nuget package, but the vssdk.targets are not sourced from it, but the build tasks are. Leading to a mismatch.

I think you'll want to change both templates so that all `vssdk.targets` are coming from the nuget package. I've found that if you change only one project (ie the project type project) to use the targets from the nuget package, the other project (i.e the project template) still loads the vssdk targets from the VSToolsPath - and this results in a different version of the tasks assembly being loaded from the version that the nuget package 
The template for the project template project, directly imports this:


```

**Comment by dazinator** [comment]
..and this is how I had to edit the project template csproj to resolve this:

```
<!--<Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" Condition="'$(VSToolsPath)' != ''" />-->
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\packages\Microsoft.VSSDK.BuildTools.15.0.26201\build\Microsoft.VSSDK.BuildTools.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\Microsoft.VSSDK.BuildTools.15.0.26201\tools\vssdk\Microsoft.VSSDK.targets'))" />
  </Target>
  <Import Project="..\..\packages\Microsoft.VSSDK.BuildTools.15.0.26201\tools\vssdk\Microsoft.VSSDK.targets" Condition="Exists('..\..\packages\Microsoft.VSSDK.BuildTools.15.0.26201\tools\vssdk\Microsoft.VSSDK.targets')" />

```

**Comment by StingyJack** [comment]
This is still happening in the VS 2017 RTW with a newly created project

**Comment by luis-cortina** [comment]
This is happened to me when upgrading from vs2015 to vs2017 using this guide:
https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017

If I follow the workaround then the build doesn't output the .vsix file. 
Any idea when this will be fixed?

**Comment by realvizu** [comment]
I'm having a similar problem:

> warning VSSDK1018: Targets version (15.0.26208.0) and build task version (15.0.26201.0) do not match.  Restarting Visual Studio could help fix this issue.

But since it's happening on Appveyor build server restarting Visual Studio is not an option.
On my dev machine it builds without a problem.
Any suggestion?

**Comment by justcla** [comment]
Ensure that ALL projects in the solution are referencing the same version of Microsoft.VsSDK.targets.

If no targets are implicitly imported at the top of the csproj, then it will default to whichever version is installed with VS2017. That might cause a mismatch.

**Comment by realvizu** [comment]
I'm using different VSSDK versions in my solution because one of the projects is set up for debugging my VSIX package in VS2015 and another one for debugging the same package in VS2017.
It works fine locally but broke on Appveyor.

Setting MsBuild log level to detailed revealed that only the first project that imports Microsoft.VsSDK.targets has $(VSToolsPath) correctly set to the VSSDK nuget package folder. All subsequently built projects have $(VSToolsPath) set to "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0" even though these projects also import Microsoft.VSSDK.BuildTools.props from the VSSDK nuget folder at the beginning of project file.
Here's the build log if someone's interested: https://ci.appveyor.com/project/realvizu/nsdepcop/build/1.7.0.102

Moving the Microsoft.VSSDK.BuildTools.props import element from the beginning of the csproj file to just before the Microsoft.VsSDK.targets import element fixed the problem. Here's the change: https://github.com/realvizu/NsDepCop/commit/27a527dcc9ce8566767c5a680b4d0f0c71c85054

**Comment by ido-ran** [comment]
I have also run into this same issue. The fact that the project template of `Extensibility/VSIX Project` is adding this `<Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" Condition="'$(VSToolsPath)' != ''" />` line to the `csproj` instead of adding the Nuget package `Microsoft.VSSDK.BuildTools` is causing pain in several scenarios:

1. When you want to upgrade the VSSDK BuildTools
2. When different team members had different versions on VSSDK BuildTools
3. When I wanted to build my project in CI server (Jenkins) without installing Visual Studio in it. I've used `Build Tools for Visual Studio 2017` but still having the Nuget package will be much better.

**Comment by AraHaan** [comment]
I just so happen to get a issue when I create a new Extension project in VS2017 15.9 Preview 2 that it then does this when creating a new Tool Window and Command:

``Package install Failed: Microsoft.VSSDK.BuildTools.15.9.4: Package restore failed. Rolling back changes for 'OpenCoverTestExplorer'.
``

And then after it tells me to reference the 3 WPF binaries then this happens:

```cs
1>C:\Users\User\Desktop\OpenCoverTestExplorer\obj\Debug\ToolWindow1Control.g.cs(41,106,41,125): error CS1069: The type name 'IComponentConnector' could not be found in the namespace 'System.Windows.Markup'. This type has been forwarded to assembly 'System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' Consider adding a reference to that assembly.
1>C:\Users\User\Desktop\OpenCoverTestExplorer\obj\Debug\ToolWindow1Control.g.cs(86,36,86,55): error CS1069: The type name 'IComponentConnector' could not be found in the namespace 'System.Windows.Markup'. This type has been forwarded to assembly 'System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' Consider adding a reference to that assembly.
1>C:\Users\User\Desktop\OpenCoverTestExplorer\obj\Debug\ToolWindow1Control.g.cs(86,14,86,55): error CS0538: 'IComponentConnector' in explicit interface declaration is not an interface
```
