### ISSUE TITLE
[Question] - Csharp capabilit and targets

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#193]
Hello,

I am wondering what the relationship is between the CSharp capability, and importing the csharp targets.

Basically, if I want my project system to compile csharp code, do I need to just add the capability, just add the targets, or add both?

The problem is, I would like my project system to compile csharp code, but importing the csharp targets is complicating things, as its causing issues like #189  - so I am just wondering if including only the csharp capability will be enough, or whether i'll also need to "steal" relevant bits from csharp targets too to get csharp code to compile. I am it is the latter, but just want to double check.

Csharp targets file is huuuge (msbuild pp:pp.txt) so having to essentially create my own slimline version is a pretty big task that I am very keen to avoid :-)

**Comment by adrianvmsft** [comment]
The Roslyn project system represents the official C# support based on CPS.

What Project System Extensibility produced before was a simplified implementation, which was fine in Visual Studio 2015.

However, in Visual Studio 2017, that is now becoming obsolete as it is being replaced by the official implementation. Currently, it powers a subset of the C# projects (.Net Core), but it will eventually expand to other flavors of the C# project system.

Because your project system enhances the C# experience, including build, I think it makes sense to leverage as much as possible from the Roslyn Project System (targets, rules, capabilities), and customize the parts specific to your scenario.

For Visual Studio 2017, you may want to clean up the XAML rule files that VS Project System generated initially as they are outdated comparing to those that Roslyn Project System currently has (ideally you should only keep those parts that are specific to your new functionality).

Regarding your question about the CSharp capability, the roslyn project system defines the CSharp capability in [Microsoft.CSharp.DesignTime.targets](https://github.com/dotnet/roslyn-project-system/blob/master/src/Targets/Microsoft.CSharp.DesignTime.targets)

A better place to ask questions about customizing the roslyn project system is on the roslyn project system GitHub, as they own the CSharp capability and the overall C# experience based on CPS.
https://github.com/dotnet/roslyn-project-system

**Comment by dazinator** [comment]
Thank you

**Comment by adrianvmsft** [comment]
You're welcome!
