### ISSUE TITLE
How to remove References node in a custom project?

### ISSUE THREAD

**Issue by andrei-aliashkevich** [Microsoft/VSProjectSystem#198]
I create my custom project type and its works fine. But each project contains a 'References' node. How can i remove this node from project.
Thanks.

**Comment by adrianvmsft** [comment]
The main reason you see the reference node is because the default project type that gets created includes C# specific targets that contain capabilities that enable C# specific features, including in this case references.

In the upcoming release of Project System Extensibility, we are going to switch to a lighter implementation - see the [WindowsScript sample](https://github.com/Microsoft/VSProjectSystem/tree/master/samples/WindowsScript)

If your project doesn't extend C# functionality, probably you won't need the dependency on C# targets (similar to the Windows Script sample above).

If however, your project is going to extend existing C# functionality, perhaps it makes sense continue to import C# specific targets; in that case you can try to remove the capabilities you don't need from your project using 
```xml
<ProjectCapability Remove="mycapability" />
```
To see everything your project imports (including capabilities), you can run on one of your projects:
```
MSBuild /pp:pp.txt
```
Here you can find [documentation](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/project_capabilities.md) about some of them.

**Comment by andrei-aliashkevich** [comment]
It's works. Thanks.
