### ISSUE TITLE
Project capability proposal: ProjectJsonConfigurations

### ISSUE THREAD

**Issue by AArnott** [Microsoft/VSProjectSystem#21]
ASP.NET vNext invented this

**Comment by Fosol** [comment]
My search for answers has led me here.

By default a DNX project nest files like config.json ->  config.debug.json

I want to be able to nest files like config.json -> config.development.debug.json

How do I do this?  I can no longer edit my project file to do this because someone has decided to extract all that functionality and hide it away in some black box.  

Feel free to point me to the right place to ask this question.

Thanks,
Jeremy

**Comment by AArnott** [comment]
@Fosol I sympathize. But this isn't the venue to get attention from ASP.NET folks, who own this. You might try filing a bug with https://github.com/aspnet/dnx/issues

**Comment by Fosol** [comment]
Thanks
