### ISSUE TITLE
Globbing and Solution Explorer

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#216]
Wondering why, when using a glob, files from the obj folder are being included.
With this glob:

```
 <ItemGroup>
    <None Include="**\*.txt" Exclude="obj\*" />
  </ItemGroup>
  ```
text file in obj folder still shows:

![image](https://cloud.githubusercontent.com/assets/3176632/24174402/520d60c0-0e88-11e7-883d-7a5a20f2bddd.png)

If you add the following to also remove the obj folder from `EmbeddedResource` and `Compile` then it works... but I am not sure why it is necessary to remove the txt file from those item types - as it isn't included in those item types in the first place?

```
<ItemGroup>
    <None Include="**\*.txt" Exclude="\obj\*" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

```

**Comment by adrianvmsft** [comment]
That is because your statement includes recursively *.txt but it excludes *.txt only directly under the obj subfolder (no recursion). The file that gets displayed is a few folders deep.
```xml
<None Include="**\*.txt" Exclude="obj\*" />
```
Problem goes away if you use recursive for exclude (note ** instead of *) :
```xml
<None Include="**\*.txt" Exclude="obj\**" />
```
The fix you mentioned above works because you have this statement, which removes using recursion:
```xml
<None Remove="obj\**" />
```

**Comment by dazinator** [comment]
Doh! Thank you. I can't believe I missed this. Thank you for your invaluable peer review service! :-)
