### ISSUE TITLE
Targets version (15.0.26201.0) and build task version (15.0.26109.1) do not match. Restarting Visual Studio could help fix this issue.

### ISSUE THREAD

**Issue by luis-cortina** [Microsoft/VSProjectSystem#228]
I'm upgrading a package from vs2015 using this guide:
https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017

When trying to build in section **Check that the extension builds correctly (as a VSIX v3)**, I get the error:
_Targets version (15.0.26201.0) and build task version (15.0.26109.1) do not match. Restarting Visual Studio could help fix this issue._

I've seen other threads talking about this but no real solution yet.

Any help.

Luis

**Comment by aienabled** [comment]
I had the same issue a few months ago when updated to 2017 RC.
https://github.com/Microsoft/VSProjectSystem/issues/170
The solution was to add nuget `Microsoft.VSSDK.BuildTools` to all the projects in the solution and then restart VS2017 (or kill all the `MSBuild` processes). This way a single version of the build targets will be used.

**Comment by luis-cortina** [comment]
Tat solved that error but now I'm getting another one:

CreatePkgDef : error : ProvideBindingRedirectionAttribute: Invalid value specified for NewVersion.

I changed all the project references to .net46 but nothing still. Any ideas?

**Comment by adrianvmsft** [comment]
Both issues are VS SDK issues, so a better place to ask these questions is https://gitter.im/Microsoft/extendvs

I did some search and encountered this solution - so perhaps you could give it a try?
https://github.com/aspnet/Razor/issues/986

If that doesn't solve the problem, you could try digging through the verbose log to see what what parameters are beeing passed to CreatePkgDev, perhaps you can spot what the issue is:
```
msbuild /v:diag > log.txt
```
Hope this helps.

**Comment by josesimoes** [comment]
When I stumble into this I open the Task manager window, kill all MSBuild processes and rebuild.
