### ISSUE TITLE
Uploading a Project Type to Visual Studio Gallery

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/VSProjectSystem#29]
With my current basic knowledge about the Project Type, it appears this project is a form of project that can be added to a VSIX.  Is it possible today (or planned later) to upload these types of projects to the Visual Studio?  What would you need to do?   Create a VSIX project in VS and add the project type project?  Is there any documentation to do this today or is it in the roadmap?  TIA

**Comment by AArnott** [comment]
The Project Type template produces two projects for you, one of them already creates a VSIX. So there is no need to create another VSIX project to reference it.

That said, a project type typically carries with it some custom build authoring, and VSIXes cannot properly place .targets and .props files in well-known locations such that your project templates can import them. So for now, you have to create an MSI project (usually using the [WiX toolset](http://wixtoolset.org/)) that will ship your build dependencies at least. Since you need an MSI, you can decide whether to bundle the VSIX in the MSI or dismantle the VSIX and use the MSI to ship everything.
