### ISSUE TITLE
Links to disabled MSDN blog pages

### ISSUE THREAD

**Issue by SabotageAndi** [Microsoft/VSProjectSystem#315]
On the following pages, there are links to disabled pages of a MSDN blog:

Pages:

- https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/contentitem_types.md
- https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/custom_item_types.md

Links:

- https://blogs.msdn.microsoft.com/vsproject/2009/06/09/platform-extensibility-part-1/
- https://blogs.msdn.microsoft.com/vsproject/2009/06/18/platform-extensibility-part-2/

Could the blog pages be enabled again or the content of them moved to somewhere else?

**Comment by drewnoakes** [comment]
@SabotageAndi #311 fixes those broken links in another document, and I pushed a commit that fixes the two you point out here. Grep suggests that's all of them.

For reference, the correct links are:

- [Platform Extensibility part 1](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-basic-project-system-part-1?view=vs-2017)
- [Platform Extensibility part 2](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-basic-project-system-part-2?view=vs-2017)

**Comment by drewnoakes** [comment]
@lifengl I don't have permission to merge the documentation fixes. There are a few outstanding PRs here with simple fixes that could probably go in with only quick reviews.

**Comment by NadiaGPLM** [comment]
The following links

Platform Extensibility part 1
Platform Extensibility part 2

quote the MPF LIbrary https://github.com/tunnelvisionlabs/MPFProj10. This library was developed in the past but now it is considere obsolete (it was managed by Microsoft until VS 2013).

So, this is the best approach yet to extend an existing project type? On the contrary, there is no documentation and no examples as extend an existing project type (for example a web application or a NET Standard project type) with the current VS Project System.

**Comment by drewnoakes** [comment]
@NadiaGPLM perhaps the replacement URLs are incorrect. Unfortunately the blogs are offline, and archive.org does not have a reference to them. The URL closely match those on docs.microsoft.com, but given the referrers are talking about XAML rules, and those target pages don't mention them at all, they may be invalid substitutes.

**Comment by NadiaGPLM** [comment]
@drewnoakes thanks for your reply.

I think that URLs probably are correctly linked,  they cover the way as create a Project Custom Type, but with MPF library.
MPF library was great and at the moment running correctly also in Visual Studio 2017 and 2019. The problem is that the new project type, as NET Standard are not supported by this library, that works on COM aggregation (and, if I hunderstand correctly this is the great different between old and new format project type).
So I am not able to find documentation or example how to create my custom project type with the new Visual Studio Project System based on flavour project (that is and existing Visual Studio project type), for example NET Standard type.
When I create with the actual Project System a custom type where the template is a NET Standard template, and running it, the project appears as a C# project.
Probably I make something wrong, but without documentation and examples is hard (or impossible!) to reach my goal.
