### ISSUE TITLE
IVsTrackProjectDocumentsEvents2.OnAfterRenameFiles is not called in projects based on CPS on directory rename/move.

### ISSUE THREAD

**Issue by NikGovorov** [Microsoft/VSProjectSystem#48]
Hi,

I'm trying to migrate my extension to Visual Studio 2015 RC and can't get IVsTrackProjectDocumentsEvents2.OnAfterRenameFiles working for folder rename/move actions in projects based on CPS(tried on ASP.NET vNext and JavaScript). Could you please confirm that it's a bug(in CPS itself or in its implementation in ASP.NET vNext, JavaScript) and will be fixed in RTM or 
it's expected behavior of new  project system and will remain in RTM?

Thanks.

Regards, 
Nikita Govorov.

**Comment by AArnott** [comment]
This is By Design. There is a more appropriate method that CPS raises instead: [IVsTrackProjectDocumentsEvents2.OnAfterRenameDirectories](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivstrackprojectdocumentsevents2.onafterrenamedirectories.aspx). I don't know why C# raised the less-appropriate event (although yes, there is a flag to indicate it's a directory even though it's calling the *Files method). 

So I suggest you modify your event handling extension to be prepared for either event to be raised.

Thanks for asking.

**Comment by NikGovorov** [comment]
Hi Andrew,

Thanks for the quick response. 

Current project system also raises [IVsTrackProjectDocumentsEvents2.OnAfterRenameDirectories ](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivstrackprojectdocumentsevents2.onafterrenamedirectories.aspx), but rgszMkOldNames and rgszMkNewNames don't include old and new files names(in folder), so it can't be used to handle mass files delete/rename/move operations.

Does it mean that the fact that CPS calls [IVsTrackProjectDocumentsEvents2.OnAfterRemoveFiles](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivstrackprojectdocumentsevents2.onafterremovefiles.aspx) on directory remove is a bug in CPS and will be changed in RTM? 

What about [IVsTrackProjectDocumentsEvents2.OnQueryRenameFiles](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivstrackprojectdocumentsevents2.onqueryrenamefiles.aspx) and [IVsTrackProjectDocumentsEvents2.OnQueryRemoveFiles](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivstrackprojectdocumentsevents2.onafterremovefiles.aspx), current version of CPS also calls them as well for directory operations, will it be aligned with new After*Files behaviour?

Looks like atm CPS behaviour is completely the same as current project system's behaviour in terms of [IVsTrackProjectDocumentsEvents2](https://msdn.microsoft.com/en-us/library/Microsoft.VisualStudio.Shell.Interop.IVsTrackProjectDocumentsEvents2_methods.aspx), except [IVsTrackProjectDocumentsEvents2.OnAfterRenameFiles](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivstrackprojectdocumentsevents2.onafterrenamefiles.aspx), probably it makes sense to fix it in CPS to avoid breaking changes? Otherwise all existing extensions will have to somehow detect CPS and have a conditional logic even only in visual studio 2015 as both project systems can be used for instance for asp.net projects.

Thoughts?

Thanks.

Regards, 
Nikita Govorov.

**Comment by AArnott** [comment]
Almost no behavior will be changing for Dev14 RTM from RC, and in particular nothing in this event interface is changing (unless ASP.NET v5 changes something on their end, which I don't expect). So what you see is what you'll get for VS2015.

Code inspection suggests that CPS itself will raise all the *Directories style methods appropriate so long as the client that is driving CPS provides the correct flags to indicate that the changed file system entity is in fact a directory rather than a file. If you can file issues for specific scenarios where we raise a *File event for a change to a directory where a *Directory event is available, we'd probably fix that for v.next (Dev15).

Our goal for CPS include to conform to precedent behaviors from older project systems where it makes sense, but it must be balanced against sacrificing accuracy, scalability, etc. In this case, so far it makes more sense for us to raise the most precise event for the kind of change (*Directory in this case because it's a directory we're talking about). We want the API to make sense for new users more than it did before. I expect that when you wrote your extension, you may have been surprised initially when you found that *File events were raised for directories instead of the *Directory events. We want to reduce the unexpected surprises for new code.

Tip: referring to "current project system" is a bit confusing (to me) since I don't know which of our several project systems you are referring to.

**Comment by NikGovorov** [comment]
In my opinion it's a bug/issue in CPS(or in new implementations of asp.net/javascript/cpp project systems based on it) and it should raise OnAfterRenameFiles on a directory move/rename actions **if a directory has any files**(as non-CPS projects do), because when you rename/move a directory you also rename/move all files in this directory. Currently CPS raises OnAfterRemoveFiles/OnQueryRemoveFiles/OnQueryRenameFiles, but doesn't raise OnAfterRenameFiles.

PS: under "current project system" I mean non-CPS: C#/VB.NET(what is the name for this project system BTW?) projects and Node.js Tools(that based on MPF) projects, but I believe other(python/php) MPF-based project systems work in the same way(raise OnAfterRemoveFiles / OnQueryRemoveFiles / OnAfterRenameFiles / OnQueryRenameFiles for non-empty folders).

**Comment by AArnott** [comment]
Our hands are somewhat tied, because the way we raise these events directly impact how SCC works (since this is the primary way SCC gets its notifications). Raising rename events for both the directory and the files within it can confuse some SCC providers, for example.

The project system behind C#/VB.NET is mostly one project system, which we refer to just as you did: "C#/VB.NET". There are also the C++ project system, F#, etc. And there are ASP.NET *web sites* (as opposed to web applications) that is a project system all its own, which internally we refer to by its original code name of "Venus".

I've opened bug 1190634 on our side to audit exactly which events we raise so we can be intentional and consistent about this if at all possible.
