### ISSUE TITLE
App designer support ?

### ISSUE THREAD

**Issue by osamakhan** [Microsoft/VSProjectSystem#86]
The intro page under "Limitations" mentions :
No (or very limited) app designer support. Project properties are typically accessed via the Property Pages dialog instead.

Could you please elaborate a bit more on what this means ? Does this limitation only apply to the design surface for "Projects"  and not the files contained within it ?

I'm currently implementing an extension that provides a XAML based UI for editing a custom file type. These file types will eventually be part of my project system. See this as an example of what I'm trying to build:
https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/WPFDesigner_XML

Will a CPS based project system not be compatible with extensions built using the regular VS SDK APIs ? Or is my scenario supported ? 

Thanks.

**Comment by adrianvmsft** [comment]
App Designer is a specialized editor that allows you to edit project properties. You can see it for example by opening the project properties for a standard C# project. If you do the same for a CPS project, you will notice that CPS uses a different dialog.

You should be able to create and use your own designer with CPS project systems.

The problem comes with some existing designers (in this particular case the App Designer) that have specific assumptions about the project system implementation. Such existing designers need to be updated so that they also work with CPS based projects.

Thanks,
Adrian

**Comment by osamakhan** [comment]
Ah thanks, I was making incorrect assumptions regarding what this limitation applied to. Thanks for the explanation.
